name: Go CI
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run:
    name: build/test/lint/fmt
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      TLACFG: ${{ secrets.TLACFG }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Passes tests
      run: go test -v ./...
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.26
        # Optional: show only new issues if it's a pull request. The default value is `false`.
        only-new-issues: true
    - name: Passes gofmt
      run: gofmt -l .